import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";

const geistSans = League_Spartan({
	variable: "--font-league-spartan",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable}antialiased`}>{children}</body>
		</html>
	);
}
